// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pipboy_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void KeyboardEnter_Animation(lv_obj_t * TargetObject, int delay);
void KeyboardLeave_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Booting
void ui_Booting_screen_init(void);
lv_obj_t * ui_Booting;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
lv_obj_t * ui_Main;
void ui_event_TabView1(lv_event_t * e);
lv_obj_t * ui_TabView1;
lv_obj_t * ui_StatsPage;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Line;
lv_obj_t * ui_HeartRate;
lv_obj_t * ui_HeartRateLabel;
lv_obj_t * ui_Temp;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_Line2;
lv_obj_t * ui_InvPage;
void ui_event_Checkbox1(lv_event_t * e);
lv_obj_t * ui_Checkbox1;
void ui_event_Checkbox3(lv_event_t * e);
lv_obj_t * ui_Checkbox3;
void ui_event_Checkbox2(lv_event_t * e);
lv_obj_t * ui_Checkbox2;
void ui_event_Checkbox4(lv_event_t * e);
lv_obj_t * ui_Checkbox4;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label51;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Image1;
lv_obj_t * ui_DataPage;
lv_obj_t * ui_UpLine;
lv_obj_t * ui_HorizontalLine;
lv_obj_t * ui_Label7;
lv_obj_t * ui_HorizontalLine2;
lv_obj_t * ui_HorizontalLine3;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label9;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label10;
lv_obj_t * ui_HorizontalLine1;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label47;
lv_obj_t * ui_HorizontalLine7;
lv_obj_t * ui_HorizontalLine8;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label48;
lv_obj_t * ui_MapPage;
lv_obj_t * ui_RadioPage;
lv_obj_t * ui_Controls;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_BatteryLabel;
lv_obj_t * ui_InfoLabel;
lv_obj_t * ui_Time;
// CUSTOM VARIABLES

// SCREEN: ui_PinControl
void ui_PinControl_screen_init(void);
lv_obj_t * ui_PinControl;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_Digital;
lv_obj_t * ui_Container3;
lv_obj_t * ui_PMW;
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_Label39;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Value;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Input;
lv_obj_t * ui_Dropdown4;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label43;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_GameSelection
void ui_GameSelection_screen_init(void);
lv_obj_t * ui_GameSelection;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label11;
lv_obj_t * ui_UpLine2;
lv_obj_t * ui_HorizontalLine4;
lv_obj_t * ui_HorizontalLine5;
lv_obj_t * ui_HorizontalLine6;
lv_obj_t * ui_Label12;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label13;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label18;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label19;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label20;
lv_obj_t * ui_HorizontalLine9;
lv_obj_t * ui_HorizontalLine10;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label15;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label14;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Roller1(lv_event_t * e);
lv_obj_t * ui_Roller1;
void ui_event_Roller2(lv_event_t * e);
lv_obj_t * ui_Roller2;
lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

// SCREEN: ui_NFC
void ui_NFC_screen_init(void);
lv_obj_t * ui_NFC;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label50;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label49;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void KeyboardEnter_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 200, 53);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void KeyboardLeave_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 53, 200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        MenuSound4(e);
    }
}

void ui_event_TabView1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MenuSound(e);
    }
}

void ui_event_Checkbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Checkbox3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Checkbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Checkbox4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        MenuSound2(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PinControl, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PinControl_screen_init);
        MenuSound3(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GameSelection, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_GameSelection_screen_init);
        MenuSound3(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Settings_screen_init);
        MenuSound3(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NFC, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_NFC_screen_init);
        MenuSound3(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Settings_screen_init);
        MenuSound3(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousSong(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SkipSong(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        PlayPause(e);
        _ui_checked_set_text_value(ui_Label5, target, ">", "||");
    }
}

void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MenuSound(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Value, target, "", "");
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Main_screen_init);
        MenuSound(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Main_screen_init);
        MenuSound(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartFlappy(e);
        MenuSound3(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartPong(e);
        MenuSound3(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartSnake(e);
        MenuSound3(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Start2048(e);
        MenuSound3(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Main_screen_init);
        MenuSound(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeVolume(e);
        MenuSound2(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleWifi(e);
        MenuSound2(e);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleBluetooth(e);
        MenuSound2(e);
    }
}

void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TimeChanged(e);
        MenuSound2(e);
    }
}

void ui_event_Roller2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TimeChanged(e);
        MenuSound2(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Main_screen_init);
        MenuSound(e);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        KeyboardEnter_Animation(ui_Keyboard1, 0);
        _ui_state_modify(ui_Button15, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_Button15, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        KeyboardLeave_Animation(ui_Keyboard1, 0);
        _ui_flag_modify(ui_Button15, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Button15, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        MenuSound3(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WriteNFCData(e);
        MenuSound(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Booting_screen_init();
    ui_Main_screen_init();
    ui_PinControl_screen_init();
    ui_GameSelection_screen_init();
    ui_Settings_screen_init();
    ui_NFC_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Booting);
}
