// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pipboy_Project

#include <Arduino.h>
#include "../settings.h"
#include "ui.h"

void StartFlappy(lv_event_t * e)
{
	StartFlappyGameMain();
}

void StartPong(lv_event_t * e)
{
	StartPongGameMain();
}

void StartSnake(lv_event_t * e)
{
	StartSnakeGameMain();
}

void Start2048(lv_event_t * e)	
{
	Start2048GameMain();
}


void WriteNFCData(lv_event_t * e)
{
	
}

void ChangeVolume(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
	settings.volume = lv_slider_get_value(slider);
	saveSettings();
	ChangeVolumeMain(settings.volume);
}

void ToggleWifi(lv_event_t * e)
{
	lv_obj_t * sw = lv_event_get_target(e);
	settings.wifiEnabled = lv_obj_has_state(sw, LV_STATE_CHECKED);
	saveSettings();
}

void ToggleBluetooth(lv_event_t * e)
{
	lv_obj_t * sw = lv_event_get_target(e);
	settings.bluetoothEnabled = lv_obj_has_state(sw, LV_STATE_CHECKED);
	saveSettings();
}

void TimeChanged(lv_event_t * e)
{
	// Get text from Roller1 and Roller2
	char hours_text[3];
	char minutes_text[3];
	lv_roller_get_selected_str(ui_Roller1, hours_text, sizeof(hours_text));
	lv_roller_get_selected_str(ui_Roller2, minutes_text, sizeof(minutes_text));
	
	// Convert text to int
	uint8_t _hours = atoi(hours_text);
	uint8_t _minutes = atoi(minutes_text);

	settings.hours = _hours;
	settings.minutes = _minutes;

	updateTimeSettings(_hours, _minutes);
}

void MenuSound(lv_event_t * e)
{
	PlayMenuSound(1);
}

void MenuSound2(lv_event_t * e)
{
	PlayMenuSound(2);
}

void MenuSound3(lv_event_t * e)
{
	PlayMenuSound(3);
}

bool bootup_sound_played = false;

void MenuSound4(lv_event_t * e)
{
	if (!bootup_sound_played) {
		PlayMenuSound(4);
		bootup_sound_played = true;
	}
}

void PreviousSong(lv_event_t * e)
{
	PreviousSongMain();
}

void SkipSong(lv_event_t * e)
{
	SkipSongMain();
}
	
void PlayPause(lv_event_t * e)
{
	PlayPauseMain();	
}