// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pipboy_Project

#ifndef _PIPBOY_PROJECT_UI_H
#define _PIPBOY_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void KeyboardEnter_Animation(lv_obj_t * TargetObject, int delay);
void KeyboardLeave_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Booting
void ui_Booting_screen_init(void);
extern lv_obj_t * ui_Booting;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
void ui_event_TabView1(lv_event_t * e);
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_StatsPage;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Line;
extern lv_obj_t * ui_HeartRate;
extern lv_obj_t * ui_HeartRateLabel;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_Line2;
extern lv_obj_t * ui_InvPage;
void ui_event_Checkbox1(lv_event_t * e);
extern lv_obj_t * ui_Checkbox1;
void ui_event_Checkbox3(lv_event_t * e);
extern lv_obj_t * ui_Checkbox3;
void ui_event_Checkbox2(lv_event_t * e);
extern lv_obj_t * ui_Checkbox2;
void ui_event_Checkbox4(lv_event_t * e);
extern lv_obj_t * ui_Checkbox4;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label51;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_DataPage;
extern lv_obj_t * ui_UpLine;
extern lv_obj_t * ui_HorizontalLine;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_HorizontalLine2;
extern lv_obj_t * ui_HorizontalLine3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_HorizontalLine1;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_HorizontalLine7;
extern lv_obj_t * ui_HorizontalLine8;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_MapPage;
extern lv_obj_t * ui_RadioPage;
extern lv_obj_t * ui_Controls;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_BatteryLabel;
extern lv_obj_t * ui_InfoLabel;
extern lv_obj_t * ui_Time;
// CUSTOM VARIABLES

// SCREEN: ui_PinControl
void ui_PinControl_screen_init(void);
extern lv_obj_t * ui_PinControl;
void ui_event_TabView2(lv_event_t * e);
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Digital;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_PMW;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Label39;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Value;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Input;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label43;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_GameSelection
void ui_GameSelection_screen_init(void);
extern lv_obj_t * ui_GameSelection;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_UpLine2;
extern lv_obj_t * ui_HorizontalLine4;
extern lv_obj_t * ui_HorizontalLine5;
extern lv_obj_t * ui_HorizontalLine6;
extern lv_obj_t * ui_Label12;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label15;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label14;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

// SCREEN: ui_NFC
void ui_NFC_screen_init(void);
extern lv_obj_t * ui_NFC;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label50;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label49;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_b65666855127377b821467c6d15734d1_png);    // assets/b65666855127377b821467c6d15734d1.png
LV_IMG_DECLARE(ui_img_thermo_png);    // assets/thermo.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
