// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pipboy_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void MenuSound4(lv_event_t * e);
void MenuSound(lv_event_t * e);
void MenuSound2(lv_event_t * e);
void MenuSound3(lv_event_t * e);
void PreviousSong(lv_event_t * e);
void SkipSong(lv_event_t * e);
void PlayPause(lv_event_t * e);
void StartFlappy(lv_event_t * e);
void ChangeVolume(lv_event_t * e);
void ToggleWifi(lv_event_t * e);
void ToggleBluetooth(lv_event_t * e);
void TimeChanged(lv_event_t * e);
void WriteNFCData(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
