// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Pipboy_Project

#include "ui.h"

void ui_GameSelection_screen_init(void)
{
    ui_GameSelection = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GameSelection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GameSelection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameSelection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameSelection, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameSelection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameSelection, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_GameSelection);
    lv_obj_set_height(ui_Button8, 24);
    lv_obj_set_width(ui_Button8, lv_pct(100));
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, -108);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button8, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "RETURN");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpLine2 = lv_obj_create(ui_GameSelection);
    lv_obj_set_width(ui_UpLine2, 2);
    lv_obj_set_height(ui_UpLine2, 75);
    lv_obj_set_x(ui_UpLine2, -133);
    lv_obj_set_y(ui_UpLine2, -39);
    lv_obj_set_align(ui_UpLine2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UpLine2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_UpLine2, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UpLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorizontalLine4 = lv_obj_create(ui_GameSelection);
    lv_obj_set_width(ui_HorizontalLine4, 50);
    lv_obj_set_height(ui_HorizontalLine4, 2);
    lv_obj_set_x(ui_HorizontalLine4, -108);
    lv_obj_set_y(ui_HorizontalLine4, -75);
    lv_obj_set_align(ui_HorizontalLine4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HorizontalLine4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HorizontalLine4, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HorizontalLine4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorizontalLine5 = lv_obj_create(ui_GameSelection);
    lv_obj_set_width(ui_HorizontalLine5, 30);
    lv_obj_set_height(ui_HorizontalLine5, 2);
    lv_obj_set_x(ui_HorizontalLine5, -118);
    lv_obj_set_y(ui_HorizontalLine5, -50);
    lv_obj_set_align(ui_HorizontalLine5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HorizontalLine5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HorizontalLine5, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HorizontalLine5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorizontalLine6 = lv_obj_create(ui_GameSelection);
    lv_obj_set_width(ui_HorizontalLine6, 30);
    lv_obj_set_height(ui_HorizontalLine6, 2);
    lv_obj_set_x(ui_HorizontalLine6, -118);
    lv_obj_set_y(ui_HorizontalLine6, -25);
    lv_obj_set_align(ui_HorizontalLine6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HorizontalLine6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HorizontalLine6, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HorizontalLine6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_GameSelection);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -52);
    lv_obj_set_y(ui_Label12, -72);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "\\GAMES");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_GameSelection);
    lv_obj_set_width(ui_Button9, 84);
    lv_obj_set_height(ui_Button9, 19);
    lv_obj_set_x(ui_Button9, -58);
    lv_obj_set_y(ui_Button9, -50);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "FLAPPY.sh");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x33FF33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
